// Generated by CoffeeScript 1.4.0
(function() {
  var exec, spawn, _ref;

  _ref = require('child_process'), spawn = _ref.spawn, exec = _ref.exec;

  task('lint', 'Lint Everything', function() {
    var lint;
    lint = exec("./node_modules/.bin/coffeelint -r Cakefile .");
    lint.stdout.on('data', function(data) {
      return console.log(data.toString());
    });
    lint.stderr.on('data', function(data) {
      return console.log(data.toString());
    });
    return console.log('Done lint');
  });

}).call(this);
